dataset:
  path: "deepglobe-road-extraction-dataset/versions/2"
  train_split_size: 0.8
  num_workers: 8
  train_size: "partial" # "full"

training:
  num_epochs: 50
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.001
  optimizer: "Adam"
  loss_function: "CenterLoss"

eval:
  labels: False
  model_path: "checkpoints/final_model/center" # "checkpoints/final_model/center" 0.7978


model:
  name: "unet"
  encoder_name: "efficientnet-b5"
  encoder_weights: "imagenet"
  activation: 'sigmoid'
  hidden_layers: 64
  in_channels: 3
  classes: 2



